[project]
name = "aoc"
version = "0.0.1"
requires-python = ">=3.9"
authors = [
  { name = "Akari202", email = "akaritwo0two@gmail.com" },
]

[project.urls]
Homepage = "https://github.com/akari202/advent"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
